name       : adapta-kde
version    : '20180828'
release    : 3
source     :
    - https://github.com/PapirusDevelopmentTeam/adapta-kde/archive/20180828.tar.gz : 7e55f4ed5c962c86d12b510bddcae1ac0018ffc95344e0b68218a98701907bdc
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Adapta KDE customization
rundeps    :
    - kvantum
description: |
    This is a port of the popular GTK theme Adapta for Plasma 5 desktop with a few additions and extras.
build      : |
    %make
install    : |
    %make_install
