name       : adapta-kde
version    : '20180618'
release    : 2
source     :
    - https://github.com/PapirusDevelopmentTeam/adapta-kde/archive/20180618.tar.gz : 33a23e4fe7f2ed0c3e7f6ef57694d56aa6961d384306ccf5aea56777eb2b094a
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Adapta KDE customization
rundeps    :
    - kvantum
description: |
    This is a port of the popular GTK theme Adapta for Plasma 5 desktop with a few additions and extras.
build      : |
    %make
install    : |
    %make_install
